name: Doxygen Documentation

on:
  push:
    branches:
      - main  # Ovaj workflow pokreće se kada se promjene pushaju u glavnu granu
  pull_request:
    branches:
      - main  # Ovaj workflow pokreće se kada se napravi pull request prema glavnoj grani

jobs:
  doxygen:
    runs-on: ubuntu-latest  # Pokrećemo workflow na najnovijoj verziji Ubuntu

    steps:
      # 1. Checkout koda
      - name: Checkout code
        uses: actions/checkout@v2  # Preuzima kod iz repozitorija

      # 2. Postavljanje JDK (ako koristite PlantUML sa JAR datotekom)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # PlantUML koristi Java, pa osiguravamo da je Java verzija 11

      # 3. Instalacija Doxygen-a
      - name: Install Doxygen
        run: sudo apt-get install doxygen  # Instaliramo Doxygen alat na virtualnu mašinu

      # 4. Instalacija Graphviz-a (ako koristite dijagrame u Doxygen-u)
      - name: Install Graphviz
        run: sudo apt-get install graphviz  # Instalira Graphviz za generiranje dijagrama (npr. dijagrami klasa)

      # 5. Instalacija PlantUML (ako koristite PlantUML za dijagrame)
      - name: Install PlantUML
        run: sudo apt-get install plantuml  # Instalira PlantUML alat na virtualnu mašinu

      # 6. Generiranje dokumentacije pomoću Doxygen-a
      - name: Generate documentation using Doxygen
        run: doxygen Doxyfile  # Pokreće Doxygen prema Doxyfile-u u repozitoriju

      # 7. Preuzimanje generirane dokumentacije kao artefakta
      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v2
        with:
          name: doxygen-docs  # Ime artefakta
          path: ./html  # Put do HTML dokumentacije (uobičajeno mjesto za izlaznu HTML dokumentaciju)

